# Generated by Django 4.0 on 2022-04-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_price'),
        ('order', '0005_alter_order_total_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='movie_names',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_movies',
        ),
        migrations.AddField(
            model_name='order',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
