# Generated by Django 4.0 on 2022-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameVietnamese', models.CharField(max_length=500)),
                ('originalTitle', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('studio', models.CharField(max_length=50)),
                ('totalTime', models.IntegerField()),
                ('yearRelease', models.IntegerField()),
                ('totalLike', models.IntegerField()),
                ('totalDislike', models.IntegerField()),
                ('imageBig', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imageSmall', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('videoUrl', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='category.category')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_movie', to='person.person')),
                ('stars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_movie', to='person.person')),
                ('writers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_movie', to='person.person')),
            ],
        ),
    ]
